### ISSUE TITLE
Master branch compilation failed

### ISSUE THREAD

**Issue by ghost** [EconomicSL/auctions-simulation-example#6]
After cloning the repo and running `sbt "run-main ContinuousDoubleAuction"`, it fails to compile. 

Seems that `ClearResult` is missing / fails to get imported.

`[error] /Users/ibillett/auctions-simulation-example/src/main/scala/ContinuousDoubleAuction.scala:20: object ClearResult is not a member of package org.economicsl.auctions.singleunit`

Full error output available at [this link](https://pastebin.com/p0wepGet).

**Comment by davidrpugh** [comment]
@ibillett this is because I have been making changes to the structure of the `esl-auctions` repo that I have not migrated to this repo yet.  Will do that today.

**Comment by davidrpugh** [comment]
@ibillett I have fixed the compiler errors and pushed to master, I leave it to you to confirm and close the issue.

**Comment by ghost** [comment]
Ok, perfect. Will check when I can.

**Comment by ghost** [comment]
I'm afraid `sbt "run-main ContinuousDoubleAuction"` is still failing to compile, see the output below.

Thought it might be a local issue if it works on your end, but tried with clean containers with the same result.

Looks like it relates to [core/Tradable.scala](https://github.com/EconomicSL/core/blob/develop/src/main/scala/org/economicsl/core/Tradable.scala#L35)?

![screen shot 2017-06-17 at 18 49 20](https://user-images.githubusercontent.com/7694011/27255056-c306413a-538d-11e7-806f-1fe9803a5f1f.png)

**Comment by davidrpugh** [comment]
@ibillett I just fixed the compiler issues but now am getting an odd run-time error related to simulations not being able to read the configuration file properly...
```bash
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'simulation'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getConfigNumber(SimpleConfig.java:219)
	at com.typesafe.config.impl.SimpleConfig.getNumber(SimpleConfig.java:225)
	at com.typesafe.config.impl.SimpleConfig.getDouble(SimpleConfig.java:241)
	at PeriodicDoubleAuctionSimulation$.delayedEndpoint$PeriodicDoubleAuctionSimulation$1(PeriodicDoubleAuctionSimulation.scala:37)
```

**Comment by davidrpugh** [comment]
@ibillett I think this might be some kind of IDE issue on my end.  I was able to run the simulations from the terminal using sbt without any issue.

**Comment by ghost** [comment]
Great job @davidrpugh all the simulations are running successfully on my end 💯 

I'll close this, tidy up the `.ipynb`, then submit a new PR with the updates.
